export const FONTS = {
  ADAGIO: 'Adagio',
  ADORNOS: 'Adornos',
  ALIENS: 'Aliens',
  ABINGDON: 'Abingdon',
  A_BIT_EMPTY: 'ABitEmpty',
  ATMOSPHERIC: 'Atmospheric',
  AUTOBUS_OMNIBUS: 'AutobusOmnibus',
  BIT_8_WONDER: 'Bit8Wonder',
  CETA_MONO: 'CetaMono',
  DIGITAL_DISCO: 'DigitalDisco',
  DOT_MATRIX: 'DotMatrix',
  GALEGA: 'Galega',
  IDENTIFICATION_MONO: 'IdentificationMono',
  MODE_NINE: 'ModeNine',
  MONKEY: 'Monkey',
  PUNK: 'Punk',
  RA_MONO_REGULAR: 'RaMonoRegular',
  SOLID_MONO_REGULAR: 'SolidMonoRegular',
  SEKUNTIA_60: 'Sekuntia60',
  THIRD_MAN: 'ThirdMan',
  VIRGO: 'Virgo',
}